### PR TITLE
Update Border.fx

### PR DESCRIPTION
**Pull request by ccritchfield**
Minor change to reduce calculations... already branching, so set border var early, then use branch to handle all border math. On special-case branch (1st branch) just set border x or y to 0 and math the other one to avoid an unnecessary calculation by 0.

### CODE REVIEW

**Comment by CeeJayDK** [comment]
Your Border.fx did not compile and did not produce the correct output after I fixed the compile errors and there were no optimizations as the original code did **not** do any unnecessary calculations by 0.

Your Ascii.fx also breaks output so the characters no longer decode correctly and your changes add 24 extra instructions to the compiled shader in performance mode and even more in edit mode, making the effect slower.

**Comment by ccritchfield** [comment]
Weird that it wouldn't compile. Then again, my process was to modify the .fx that ReShade installed using notepad++, and then run the game ReShade was attached to to see if ReShade could compile the shader. I was using an older version of ReShade with Elder Scrolls Daggerfall when I started messing with these. It compiled and worked. Then installed latest version of ReShade and tested changes with Skyrim. It worked, too. But, my test for "optimization" was to simply check ReShade's stats to see how the milliseconds were doing in processing chain. I'm completely amateur when it comes to shader coding, but am interested in getting into it more. What software do you have installed to be able to compile shaders and see instructions breakdown? I've been wanting to move to that level of shader development, but clueless where to begin. Any feedback is appreciated. Thanks.

**Comment by CeeJayDK** [comment]
It would not compile because you forgot to add { } brackets to your if and else statements.
If left out if and else will regard the next line of code as part of their block.
I sometimes leave out the brackets when I only need one line of code.
You however used more lines and left out the brackets and so it failed to compile.

I use Visual Studio Code as my editor though notepad++ (set to C highlighting or with a mod to enable hlsl highlighting) is also a good option for an editor.

When I want to test the code I save it and switch to a demo or game I have running in another process, which has Reshade installed to it.
I then trigger a reload in Reshade (you can make a keybind for this) and Reshade will then compile all the shaders including mine.
It will tell me if it will not compile.
I can also right click any effect and open Reshades own editor which I use for quick edits or for performance tweaking which can be easier to do from within Reshade.

Rightclicking an active effect in Reshade also lets you see the compiled ASM output. That tells you how many instructions it compiled to which is a decent indication of performance. Fewer instructions is usually faster, though some instructions take longer to complete than others.

Reshades performance statistics are not entirely accurate (that's an understatement) and they come from the API being used and so can vary.
Newer API are usually more accurate.
Since they cannot be fully trusted I recommend using a demo with a scene that has a stable FPS.
More FPS **is** faster and you can calculate how many ms the change is if you want to get the exact ms improvement.
Note however that code that is faster on one GPU or even driver is not always on another. Some code might be faster on a AMD card and some might be faster on an Nvidia card, but in general fewer instructions means faster code.
To make things even more complex the ASM the compiler produces is further optimized and compiles to vendor specific hardware instructions. There are special tools for some cards and drivers that allows you to see what exact hardware instructions the code compiles to but not for all.

So for most work I look at compiler ASM instructions and FPS and leave it at that.

If you need help on some code or a mentor to teach you more about coding for Reshade, I suggest dropping by on our discord and ask in the #code-chat room. I'm not always there, but there is usually always a few developers online that can help.

**Comment by ccritchfield** [comment]
This was really helpful information. Thanks, CeeJay

**Pull request closed without merging**
